LeanOnMe/Controllers/MyMedicineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataAccess.Models;
using PagedList;
using System.Data.Entity;

namespace LeanOnMe.Controllers
{
    public class MyMedicineController : Controller
    {
        // GET: MyMedicine
        LeanOnMeEntities db = new LeanOnMeEntities();
        public ActionResult Index(string sortOrder, string currentFilter, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.MedicineSort = String.IsNullOrEmpty(sortOrder) ? "Question_Desc" : "";
            ViewBag.DosageSort = sortOrder == "QuestionSortAsc" ? "QuestionSortDesc" : "QuestionSortAsc";
            ViewBag.DosageTimesSort = sortOrder == "LocationSortAsc" ? "LocationSortDesc" : "LocationSortAsc";
            ViewBag.DoctorSort = sortOrder == "InfoSortAsc" ? "InfoSortDesc" : "InfoSortAsc";
            ViewBag.UserSort = sortOrder == "AddSortAsc" ? "AddSortDesc" : "AddSortAsc";

            var employees = from e in db.MyMedicines
                            select e;

            switch (sortOrder)
            {
                case "Question_Desc":
                    employees = employees.OrderByDescending(s => s.MedicineName);
                    break;
                case "QuestionSortAsc":
                    employees = employees.OrderBy(s => s.DosagePerPill);
                    break;
                case "QuestionSortDesc":
                    employees = employees.OrderByDescending(s => s.DosagePerPill);
                    break;

                case "LocationSortAsc":
                    employees = employees.OrderBy(s => s.TimesTaken);
                    break;
                case "LocationSortDesc":
                    employees = employees.OrderByDescending(s => s.TimesTaken);
                    break;
                case "InfoSortAsc":
                    employees = employees.OrderBy(s => s.PrescribedDoctor);
                    break;
                case "InfoSortDesc":
                    employees = employees.OrderByDescending(s => s.PrescribedDoctor);
                    break;
                case "AddSortAsc":
                    employees = employees.OrderBy(s => s.UserRegistration.UserName);
                    break;
                case "AddSortDesc":
                    employees = employees.OrderByDescending(s => s.UserRegistration.UserName);
                    break;

                default:
                    employees = employees.OrderBy(s => s.MedicineName);
                    break;
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            string role = Convert.ToString(Session["RoleName"]);
            int ids = Convert.ToInt16(Session["UserID"]);
            if (role != "Admin")
            {
                employees = employees.Where(m => m.UserRegistration.Registration.UserID == ids);
            }
            return View(employees.ToPagedList(pageNumber, pageSize));
        }
        
        // GET: MyMedicine/Create
        public ActionResult Create()
        {
            int helper = Convert.ToInt32(Session["UserID"]);
            ViewBag.HelperID = new SelectList(db.Registrations.Where(m => m.Role != "Admin"), "UserID", "UserName");
            string role = Convert.ToString(Session["RoleName"]);
            if (role != "Admin")
            {
                ViewBag.UserID = new SelectList(db.UserRegistrations.Where(m => m.HelperID == helper), "UserID", "UserName");
            }
            else
            {
                ViewBag.UserID = new SelectList(db.UserRegistrations, "UserID", "UserName");
            }
            return View();
        }

        // POST: MyMedicine/Create
        [HttpPost]
        public ActionResult Create(MyMedicine list)
        {
            try
            {
                long count = 0;
                if (db.MyMedicines.Any())
                {
                    count = db.MyMedicines.Max(m => m.MedicineID);
                    count++;
                }
                else
                {
                    count = 1000;
                }
                var file = Request.Files["file"];
                string name = "";
                if (file.ContentLength > 0)
                {
                    string extension = System.IO.Path.GetExtension(file.FileName);
                    name = Convert.ToString(count) + extension;
                    string pic = System.IO.Path.GetFileName(file.FileName);
                    string path = System.IO.Path.Combine(Server.MapPath("~/Uploads/MyMedicines"), name);
                    file.SaveAs(path);
                    list.Images = name;
                }
                string role = Convert.ToString(Session["RoleName"]);
                if (role == "Admin")
                {
                    if (list.MedicineName == "" || list.MedicineName == null)
                    {
                        int helper = Convert.ToInt32(list.HelperID);
                        ViewBag.HelperID = new SelectList(db.Registrations.Where(m => m.Role != "Admin"), "UserID", "UserName", list.HelperID);
                        ViewBag.UserID = new SelectList(db.UserRegistrations.Where(m => m.HelperID == helper), "UserID", "UserName");
                        return View();
                    }
                }
                if (ModelState.IsValid)
                {
                    if (list.HelperID <= 0 || list.HelperID == null)
                    {
                        list.HelperID = Convert.ToInt32(Session["UserID"]);
                    }                
                    db.MyMedicines.Add(list);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(list);
            }
            catch
            {
                return View(list);
            }
        }

        // GET: MyMedicine/Edit/5
        public ActionResult Edit(int id)
        {
            int helper = Convert.ToInt32(Session["UserID"]);
            var lst = db.MyMedicines.Find(id);
            Session["listuser"] = lst.HelperID;
            ViewBag.HelperID = new SelectList(db.Registrations.Where(m => m.Role != "Admin"), "UserID", "UserName", lst.HelperID);
            ViewBag.UserID = new SelectList(db.UserRegistrations.Where(m => m.HelperID == lst.HelperID), "UserID", "UserName", lst.UserID);
            return View(lst);
        }

        // POST: MyMedicine/Edit/5
        [HttpPost]
        public ActionResult Edit(MyMedicine list)
        {
            try
            {
                int user = Convert.ToInt32(Session["listuser"]);
                string role = Convert.ToString(Session["RoleName"]);
                var file = Request.Files["file"];
                string name = "";
                if (file.ContentLength > 0)
                {
                    string extension = System.IO.Path.GetExtension(file.FileName);
                    name = Convert.ToString(list.MedicineID) + extension;
                    string pic = System.IO.Path.GetFileName(file.FileName);
                    string path = System.IO.Path.Combine(Server.MapPath("~/Uploads/MyMedicines"), name);
                    file.SaveAs(path);
                    list.Images = name;
                }
                else
                {
                    list.Images = Convert.ToString(list.Images);
                }
                if (role == "Admin")
                {
                    if (user != list.HelperID)
                    {
                        int helper = Convert.ToInt32(list.HelperID);
                        ViewBag.HelperID = new SelectList(db.Registrations, "UserID", "UserName", list.HelperID);
                        ViewBag.UserID = new SelectList(db.UserRegistrations.Where(m => m.HelperID == helper), "UserID", "UserName");
                        Session["listuser"] = list.HelperID;
                        return View(list);
                    }
                }
                if (ModelState.IsValid)
                {
                    db.Entry(list).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(list);
            }
            catch
            {
                return View(list);
            }
        }

        // GET: MyMedicine/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                MyMedicine lst = db.MyMedicines.Find(id);
                db.MyMedicines.Remove(lst);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View();
            }
        }       
    }
}

LeanOnMe/Views/MyMedicine/Create.cshtml
@model DataAccess.Models.MyMedicine
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="http://maps.googleapis.com/maps/api/js"></script>

    <style>
        #maps {
            height: 600px !important;
            width: 700px !important;
        }
    </style>
}
<div class="container">
    <div class="section">
        <div class="section" id="basic-form">
            <div class="row">
                <div class="col s12 m12 l10">
                    <div class="card-panel">
                        <h4 class="header2">Add Medicines</h4>
                        <div class="row">
                            @using (Html.BeginForm("Create", "MyMedicine", FormMethod.Post, new { enctype = "multipart/form-data",id="TheForm" }))
                            {
                                <table class="rwd-table">
                                    @{
                                        string role = Convert.ToString(Session["RoleName"]);
                                        if (role == "Admin")
                                        {
                                            <tr>
                                                <td>
                                                    Helper
                                                </td>
                                                <td>
                                                    @Html.DropDownList("HelperID", (SelectList)ViewBag.HelperID, new { onchange = "document.getElementById('TheForm').submit();" })
                                                </td>
                                            </tr>
                                        }
                                    }
                                    <tr>
                                        <td>
                                            User
                                        </td>
                                        <td>
                                            @Html.DropDownList("UserID", (SelectList)ViewBag.UserID)
                                        </td>

                                        <td>
                                            Medicine Name
                                        </td>
                                        <td>
                                            @Html.TextBoxFor(m => m.MedicineName)
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Dosage Per Pill
                                        </td>
                                        <td>
                                            @Html.TextBoxFor(m => m.DosagePerPill)
                                        </td>

                                        <td>
                                            Pills Per Dose
                                        </td>
                                        <td>
                                            @Html.TextBoxFor(m => m.PillsPerDose)
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Days to Take
                                        </td>
                                        <td>
                                            @Html.TextBoxFor(m => m.Weekdays)
                                        </td>

                                        <td>
                                            Times Taken
                                        </td>
                                        <td>
                                            @Html.TextBoxFor(m => m.TimesTaken)
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Prescribed By
                                        </td>
                                        <td>
                                            @Html.TextBoxFor(m => m.PrescribedDoctor)
                                        </td>

                                        <td>
                                            Prescriber Contact
                                        </td>
                                        <td>
                                            @Html.TextBoxFor(m => m.DoctorContact)
                                        </td>
                                    </tr>                                   
                                    <tr>
                                        <td>
                                            Image
                                        </td>
                                        <td>
                                            <input type="file" name="file" id="file" accept="images/*" />
                                        </td>
                                    </tr>
                                </table>
                                <div class="row">
                                    <div class="input-field col s12">
                                        <div class=" col s6 ">
                                            <a href="@Url.Action("Index")" class="btn cyan waves-effect waves-light left">
                                                Go Back<i class="mdi-content-send right"></i>
                                            </a>
                                        </div>
                                        <div class=" col s6">
                                            <button name="action" type="submit" class="btn cyan waves-effect waves-light right">Submit <i class="mdi-content-send right"></i></button>
                                        </div>
                                    </div>
                                </div>

                            }
                        </div>
                    </div>
                    <div class="card-content">
                        <a class="btn-floating btn-move-up waves-effect waves-light darken-2 right"><i class="mdi-content-add activator add-row-btn"></i></a>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

LeanOnMe/Views/MyMedicine/Edit.cshtml
@model DataAccess.Models.MyMedicine
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="http://maps.googleapis.com/maps/api/js"></script>

    <style>
        #maps {
            height: 600px !important;
            width: 700px !important;
        }
    </style>
}
<div class="container">
    <div class="section">
        <div class="section" id="basic-form">
            <div class="row">
                <div class="col s12 m12 l10">
                    <div class="card-panel">
                        <h4 class="header2">Update Medicine Details</h4>
                        <div class="row">
                            @using (Html.BeginForm("Edit", "MyMedicine", FormMethod.Post, new { enctype = "multipart/form-data", id = "TheForm" }))
                            {
                                @Html.HiddenFor(m => m.MedicineID)
                                @Html.HiddenFor(m => m.Images)
                                <table class="rwd-table">
                                    @{
                                        string role = Convert.ToString(Session["RoleName"]);
                                        if (role == "Admin")
                                        {
                                            <tr>
                                                <td>
                                                    Helper
                                                </td>
                                                <td>
                                                    @Html.DropDownList("HelperID", (SelectList)ViewBag.HelperID, new { onchange = "document.getElementById('TheForm').submit();" })
                                                </td>
                                            </tr>
                                        }
                                    }
                                    <tr>
                                        <td>
                                            User
                                        </td>
                                        <td>
                                            @Html.DropDownList("UserID", "")
                                        </td>

                                        <td>
                                            Medicine Name
                                        </td>
                                        <td>
                                            @Html.TextBoxFor(m => m.MedicineName)
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Dosage Per Pill
                                        </td>
                                        <td>
                                            @Html.TextBoxFor(m => m.DosagePerPill)
                                        </td>

                                        <td>
                                            Pills Per Dose
                                        </td>
                                        <td>
                                            @Html.TextBoxFor(m => m.PillsPerDose)
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Days to Take
                                        </td>
                                        <td>
                                            @Html.TextBoxFor(m => m.Weekdays)
                                        </td>

                                        <td>
                                            Times Taken
                                        </td>
                                        <td>
                                            @Html.TextBoxFor(m => m.TimesTaken)
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Prescribed By
                                        </td>
                                        <td>
                                            @Html.TextBoxFor(m => m.PrescribedDoctor)
                                        </td>

                                        <td>
                                            Prescriber Contact
                                        </td>
                                        <td>
                                            @Html.TextBoxFor(m => m.DoctorContact)
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Image
                                        </td>
                                        <td>
                                            <input type="file" name="file" id="file" accept="images/*" />
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div class="row margin">
                                                <div class="input-field col s12">
                                                    <img src="~/Uploads/MyMedicines/@Model.Images" alt="" height="120px" width="120px" />
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                </table>
                                <div class="row">
                                    <div class="input-field col s12">
                                        <div class=" col s6 ">
                                            <a href="@Url.Action("Index")" class="btn cyan waves-effect waves-light left">
                                                Go Back<i class="mdi-content-send right"></i>
                                            </a>
                                        </div>
                                        <div class=" col s6">
                                            <button name="action" type="submit" class="btn cyan waves-effect waves-light right">Save <i class="mdi-content-send right"></i></button>
                                        </div>
                                    </div>
                                </div>

                                        }
                        </div>
                    </div>
                    <div class="card-content">
                        <a class="btn-floating btn-move-up waves-effect waves-light darken-2 right"><i class="mdi-content-add activator add-row-btn"></i></a>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $("#HelperID").change(function () {
            $("#MyForm").submit();
        });
    });
</script>

LeanOnMe/Views/MyMedicine/Index.cshtml
@model PagedList.IPagedList<DataAccess.Models.MyMedicine>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
}
<div class="container">
    <div class="section">
        <div class="section" id="basic-form">
            <div class="row">
                <fieldset>
                    <legend>My Medicine List</legend>
                    <div class="col-lg-2 col-md-2 col-sm-2 no-right-pad ">
                        <input type="text" class="validate" placeholder="Search" style="width:20%" id="search" />
                        @using (Html.BeginForm("Create", "MyMedicine", FormMethod.Get))
                        {
                            <button name="action" type="submit" class="btn cyan waves-effect waves-light right" style="margin-top: -45px;">Add Medicines<i class="mdi-content-send right"></i></button>
                        }
                    </div>
                    <table class="table table-striped responsive-utilities jambo_table bulk_action" id="tblsearch">
                        <thead>
                            <tr>
                                <th>
                                    @Html.ActionLink("Medicine", "Index", new { sortOrder = ViewBag.MedicineSort, currentFilter = ViewBag.CurrentFilter })
                                </th>
                                <th>
                                    @Html.ActionLink("Dosage", "Index", new { sortOrder = ViewBag.DosageSort, currentFilter = ViewBag.CurrentFilter })
                                </th>
                                <th class="hidden-xs">
                                    @Html.ActionLink("Dosage Times", "Index", new { sortOrder = ViewBag.DosageTimesSort, currentFilter = ViewBag.CurrentFilter })
                                </th>
                                <th class="hidden-xs">
                                    @Html.ActionLink("Prescribed Doctor", "Index", new { sortOrder = ViewBag.DoctorSort, currentFilter = ViewBag.CurrentFilter })
                                </th>
                                <th>
                                    @Html.ActionLink("User", "Index", new { sortOrder = ViewBag.UserSort, currentFilter = ViewBag.CurrentFilter })
                                </th>
                                <th>
                                    Action
                                </th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.MedicineName)
                                    </td>

                                    <td>
                                        @Html.DisplayFor(modelItem => item.DosagePerPill)
                                    </td>

                                    <td class="hidden-xs">
                                        @Html.DisplayFor(modelItem => item.TimesTaken)
                                    </td>

                                    <td class="hidden-xs">
                                        @Html.DisplayFor(modelItem => item.PrescribedDoctor)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.UserRegistration.UserName)
                                    </td>
                                    <td>
                                        @Html.ActionLink("Edit", "Edit", new { id = item.MedicineID }) |
                                        @Html.ActionLink("Delete", "Delete", new { id = item.MedicineID }, new { @class = "Clicklink" })
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <p>
                        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
                    </p>
                    @Html.PagedListPager(Model, page => Url.Action("Index",
                    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
                </fieldset>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $('#search').keyup(function () {
            searchTable($(this).val());
        });
        $(".Clicklink").click(function () {
            var r = confirm("Are you sure you want to delete this?");
            if (r == true) {
                return true;
            } else {
                return false;
            }
        });
    });
    function searchTable(inputVal) {
        var table = $('#tblsearch');
        table.find('tbody tr').each(function (index, row) {
            var allCells = $(row).find('td');
            if (allCells.length > 0) {
                var found = false;
                allCells.each(function (index, td) {
                    var regExp = new RegExp(inputVal, 'i');
                    if (regExp.test($(td).text())) {
                        found = true;
                        return false;
                    }
                });
                if (found == true) $(row).show(); else $(row).hide();
            }
        });
    }
</script>