LeanOnMe/Controllers/MyCallTreeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataAccess.Models;
using PagedList;
using System.Data.Entity;

namespace LeanOnMe.Controllers
{
    public class MyCallTreeController : BaseController
    {
        // GET: MyCallTree
        public ActionResult Index(string sortOrder, string currentFilter, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.MyHelperSort = String.IsNullOrEmpty(sortOrder) ? "Question_Desc" : "";
            ViewBag.RoleSort = sortOrder == "QuestionSortAsc" ? "QuestionSortDesc" : "QuestionSortAsc";
            ViewBag.OrganisationSort = sortOrder == "LocationSortAsc" ? "LocationSortDesc" : "LocationSortAsc";
            ViewBag.UserSort = sortOrder == "InfoSortAsc" ? "InfoSortDesc" : "InfoSortAsc";
            ViewBag.HelperSort = sortOrder == "AddSortAsc" ? "AddSortDesc" : "AddSortAsc";

            var employees = from e in db.MyCallTrees
                            select e;
            switch (sortOrder)
            {
                case "Question_Desc":
                    employees = employees.OrderByDescending(s => s.Name);
                    break;
                case "QuestionSortAsc":
                    employees = employees.OrderBy(s => s.Role);
                    break;
                case "QuestionSortDesc":
                    employees = employees.OrderByDescending(s => s.Role);
                    break;

                case "LocationSortAsc":
                    employees = employees.OrderBy(s => s.Organistaion);
                    break;
                case "LocationSortDesc":
                    employees = employees.OrderByDescending(s => s.Organistaion);
                    break;
                case "InfoSortAsc":
                    employees = employees.OrderBy(s => s.UserRegistration.UserName);
                    break;
                case "InfoSortDesc":
                    employees = employees.OrderByDescending(s => s.UserRegistration.UserName);
                    break;
                case "AddSortAsc":
                    employees = employees.OrderBy(s => s.Registration.UserName);
                    break;
                case "AddSortDesc":
                    employees = employees.OrderByDescending(s => s.Registration.UserName);
                    break;

                default:
                    employees = employees.OrderBy(s => s.Name);
                    break;
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            string role = Convert.ToString(Session["RoleName"]);
            int ids = Convert.ToInt16(Session["UserID"]);
            if (role != "Admin")
            {
                employees = employees.Where(m => m.UserRegistration.Registration.UserID == ids);
            }
            return View(employees.ToPagedList(pageNumber, pageSize));
        }
                
        // GET: MyCallTree/Create
        public ActionResult Create()
        {
            int helper = Convert.ToInt32(Session["UserID"]);
            ViewBag.HelperID = new SelectList(db.Registrations.Where(m => m.Role != "Admin"), "UserID", "UserName");
            string role = Convert.ToString(Session["RoleName"]);
            if (role != "Admin")
            {
                ViewBag.UserID = new SelectList(db.UserRegistrations.Where(m => m.HelperID == helper), "UserID", "UserName");
            }
            else
            {
                ViewBag.UserID = new SelectList(db.UserRegistrations, "UserID", "UserName");
            }
            return View();
        }

        // POST: MyCallTree/Create
        [HttpPost]
        public ActionResult Create(MyCallTree list)
        {
            try
            {
                string role = Convert.ToString(Session["RoleName"]);
                long count = 0;
                if (db.MyCallTrees.Any())
                {
                    count = db.MyCallTrees.Max(m => m.CallTreeID);
                    count++;
                }
                else
                {
                    count = 1000;
                }
                var file = Request.Files["file"];
                string name = "";
                if (file.ContentLength > 0)
                {
                    string extension = System.IO.Path.GetExtension(file.FileName);
                    name = Convert.ToString(count) + extension;
                    string pic = System.IO.Path.GetFileName(file.FileName);
                    string path = System.IO.Path.Combine(Server.MapPath("~/Uploads/MyCallTree"), name);
                    file.SaveAs(path);
                    list.Images = name;
                }
                if (role == "Admin")
                {
                    if (list.Name == "" || list.Name == null || ModelState.IsValid == false)
                    {
                        int helper = Convert.ToInt32(list.HelperID);
                        ViewBag.HelperID = new SelectList(db.Registrations.Where(m => m.Role != "Admin"), "UserID", "UserName", list.HelperID);
                        ViewBag.UserID = new SelectList(db.UserRegistrations.Where(m => m.HelperID == helper), "UserID", "UserName");
                        return View(list);
                    }
                }
                if (ModelState.IsValid)
                {
                    if (list.HelperID <= 0 || list.HelperID == null)
                    {
                        list.HelperID = Convert.ToInt32(Session["UserID"]);
                    }
                    db.MyCallTrees.Add(list);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(list);
            }
            catch
            {
                return View(list);
            }
        }

        // GET: MyCallTree/Edit/5
        public ActionResult Edit(int id)
        {
            int helper = Convert.ToInt32(Session["UserID"]);
            var lst = db.MyCallTrees.Find(id);
            Session["listuser"] = lst.HelperID;
            ViewBag.HelperID = new SelectList(db.Registrations.Where(m => m.Role != "Admin"), "UserID", "UserName", lst.HelperID);
            ViewBag.UserID = new SelectList(db.UserRegistrations.Where(m => m.HelperID == lst.HelperID), "UserID", "UserName", lst.UserID);
            return View(lst);
        }

        // POST: MyCallTree/Edit/5
        [HttpPost]
        public ActionResult Edit(MyCallTree list)
        {
            try
            {
                int user = Convert.ToInt32(Session["listuser"]);
                string role = Convert.ToString(Session["RoleName"]);
                var file = Request.Files["file"];
                string name = "";
                if (file.ContentLength > 0)
                {
                    string extension = System.IO.Path.GetExtension(file.FileName);
                    name = Convert.ToString(list.CallTreeID) + extension;
                    string pic = System.IO.Path.GetFileName(file.FileName);
                    string path = System.IO.Path.Combine(Server.MapPath("~/Uploads/MyCallTree"), name);
                    file.SaveAs(path);
                    list.Images = name;
                }
                else
                {
                    list.Images = Convert.ToString(list.Images);
                }
                if (role == "Admin")
                {
                    if (user != list.HelperID)
                    {
                        int helper = Convert.ToInt32(list.HelperID);
                        ViewBag.HelperID = new SelectList(db.Registrations, "UserID", "UserName", list.HelperID);
                        ViewBag.UserID = new SelectList(db.UserRegistrations.Where(m => m.HelperID == helper), "UserID", "UserName");
                        Session["listuser"] = list.HelperID;
                        return View(list);
                    }
                }
                if (ModelState.IsValid)
                {
                    db.Entry(list).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(list);
            }
            catch
            {
                return View(list);
            }
        }

        // GET: MyCallTree/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                MyCallTree lst = db.MyCallTrees.Find(id);
                db.MyCallTrees.Remove(lst);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {                
                return View();
            }
        }        
    }
}

LeanOnMe/Views/MyCallTree/Create.cshtml
@model DataAccess.Models.MyCallTree
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="http://maps.googleapis.com/maps/api/js"></script>
    <style>
        #maps {
            height: 600px !important;
            width: 700px !important;
        }
    </style>
}
<div class="container">
    <div class="section">
        <div class="section" id="basic-form">
            <div class="row">
                <div class="col s12 m12 l10">
                    <div class="card-panel">
                        <h4 class="header2">Add New Caller</h4>
                        <div class="row">
                            @using (Html.BeginForm("Create", "MyCallTree", FormMethod.Post, new { enctype = "multipart/form-data", id = "TheForm" }))
                            {
                                <table class="rwd-table">
                                    @{
                                        string role = Convert.ToString(Session["RoleName"]);
                                        if (role == "Admin")
                                        {
                                            <tr>
                                                <td>
                                                    Helper
                                                </td>
                                                <td>
                                                    @Html.DropDownList("HelperID", (SelectList)ViewBag.HelperID, new { onchange = "document.getElementById('TheForm').submit();" })
                                                </td>
                                            </tr>
                                        }
                                    }
                                    <tr>
                                        <td>
                                            User
                                        </td>
                                        <td>
                                            @Html.DropDownList("UserID", (SelectList)ViewBag.UserID)
                                        </td>

                                        <td>
                                            Caller Name
                                        </td>
                                        <td>
                                            @Html.TextBoxFor(m => m.Name)
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Role
                                        </td>
                                        <td>
                                            @Html.TextBoxFor(m => m.Role)
                                        </td>

                                        <td>
                                            Organisation
                                        </td>
                                        <td>
                                            @Html.TextBoxFor(m => m.Organistaion)
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Street Address
                                        </td>
                                        <td>
                                            @Html.TextBoxFor(m => m.StreetAddress)
                                        </td>

                                        <td>
                                            City
                                        </td>
                                        <td>
                                            @Html.TextBoxFor(m => m.City)
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            State
                                        </td>
                                        <td>
                                            @Html.TextBoxFor(m => m.State)
                                        </td>

                                        <td>
                                            Zip Code
                                        </td>
                                        <td>
                                            @Html.TextBoxFor(m => m.ZipCode)
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Home Phone
                                        </td>
                                        <td>
                                            @Html.TextBoxFor(m => m.HomeNumber)
                                        </td>

                                        <td>
                                            Business Phone
                                        </td>
                                        <td>
                                            @Html.TextBoxFor(m => m.BusinessNumber)
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Mobile
                                        </td>
                                        <td>
                                            @Html.TextBoxFor(m => m.Mobile)
                                        </td>
                                        <td>
                                            Notes
                                        </td>
                                        <td>
                                            @Html.TextBoxFor(m => m.Notes)
                                        </td>
                                    </tr>
                                    <tr id="loc">
                                        <td>
                                            Location
                                        </td>
                                        <td>
                                            @Html.TextBoxFor(m => m.Coordinates, new { id = "locations" })
                                        </td>
                                        <td>
                                            Image
                                        </td>
                                        <td>
                                            <input type="file" name="file" id="file" accept="images/*" />
                                        </td>
                                    </tr>

                                </table>
                                <div class="section" id="modals-demo">
                                    <div class="row">
                                        <div class="col s12 m8 l9">
                                            <p>
                                                <a href="#modal1" id="setloc" style="display:none" class="waves-effect waves-light btn modal-trigger  light-blue" onclick=' return initialize();'>Location</a>
                                            </p>

                                        </div>
                                    </div>
                                </div>

                                <div class="row">

                                    <div class="input-field col s12">
                                        <div class=" col s6 ">
                                            @*<button name="action" type="submit" class="btn cyan waves-effect waves-light left" onclick="window.location.href = '/AdminQuestion/Index';">Go Back<i class="mdi-content-send right"></i></button>*@

                                            <a href="@Url.Action("Index")" class="btn cyan waves-effect waves-light left">
                                                Go Back<i class="mdi-content-send right"></i>
                                            </a>
                                        </div>
                                        <div class=" col s6">
                                            <button name="action" type="submit" class="btn cyan waves-effect waves-light right">Submit <i class="mdi-content-send right"></i></button>
                                        </div>
                                    </div>
                                </div>

                                        }
                        </div>
                    </div>
                    <div class="card-content">
                        <a class="btn-floating btn-move-up waves-effect waves-light darken-2 right"><i class="mdi-content-add activator add-row-btn"></i></a>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
<div class="modalTest" id="modal1" style="width:700px;height:600px">
    <div id="maps">
    </div>
</div>
<script type="text/javascript">
    var map;
    function initialize() {
        navigator.geolocation.getCurrentPosition(success);
        function success(position) {
            latlngs = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
            var mapProp = {
                center: latlngs, //Pick up user current Location
                zoom: 5,
                mapTypeId: google.maps.MapTypeId.G_NORMAL_MAP
            };
            map = new google.maps.Map(document.getElementById("maps"), mapProp);
            google.maps.event.addListener(map, 'click', function (e) {
                var latLng = e.latLng;
                $('#locations').val(latLng);
                $('#loc').css('display', 'table-row');
                $('#modal1').hide();
                $('#lean-overlay').hide();
            });
        }
    }
    // google.maps.event.addDomListener(window, "load", initialize);
    google.maps.event.trigger(map, 'resize');
</script>
<script>
    $(document).ready(function () {
        $("#locations").on('click', function () {
            $('#setloc').click();
        });
    });
</script>

LeanOnMe/Views/MyCallTree/Edit.cshtml
@model DataAccess.Models.MyCallTree
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="http://maps.googleapis.com/maps/api/js"></script>

    <style>
        #maps {
            height: 600px !important;
            width: 700px !important;
        }
    </style>
}
<div class="container">
    <div class="section">
        <div class="section" id="basic-form">
            <div class="row">
                <div class="col s12 m12 l10">
                    <div class="card-panel">
                        <h4 class="header2">Modify Caller Details</h4>
                        <div class="row">
                            @using (Html.BeginForm("Edit", "MyCallTree", FormMethod.Post, new { enctype = "multipart/form-data", id = "TheForm" }))
                            {
                                @Html.HiddenFor(m => m.CallTreeID)
                                @Html.HiddenFor(m => m.Images)
                                <table class="rwd-table">
                                    @{
                                        string role = Convert.ToString(Session["RoleName"]);
                                        if (role == "Admin")
                                        {
                                            <tr>
                                                <td>
                                                    Helper
                                                </td>
                                                <td>
                                                    @Html.DropDownList("HelperID", (SelectList)ViewBag.HelperID, new { onchange = "document.getElementById('TheForm').submit();" })
                                                </td>
                                            </tr>
                                        }
                                    }
                                    <tr>
                                        <td>
                                            User
                                        </td>
                                        <td>
                                            @Html.DropDownList("UserID", "")
                                        </td>

                                        <td>
                                            Caller Name
                                        </td>
                                        <td>
                                            @Html.TextBoxFor(m => m.Name)
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Role
                                        </td>
                                        <td>
                                            @Html.TextBoxFor(m => m.Role)
                                        </td>

                                        <td>
                                            Organisation
                                        </td>
                                        <td>
                                            @Html.TextBoxFor(m => m.Organistaion)
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Street Address
                                        </td>
                                        <td>
                                            @Html.TextBoxFor(m => m.StreetAddress)
                                        </td>

                                        <td>
                                            City
                                        </td>
                                        <td>
                                            @Html.TextBoxFor(m => m.City)
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            State
                                        </td>
                                        <td>
                                            @Html.TextBoxFor(m => m.State)
                                        </td>

                                        <td>
                                            Zip Code
                                        </td>
                                        <td>
                                            @Html.TextBoxFor(m => m.ZipCode)
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Home Phone
                                        </td>
                                        <td>
                                            @Html.TextBoxFor(m => m.HomeNumber)
                                        </td>

                                        <td>
                                            Business Phone
                                        </td>
                                        <td>
                                            @Html.TextBoxFor(m => m.BusinessNumber)
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Mobile
                                        </td>
                                        <td>
                                            @Html.TextBoxFor(m => m.Mobile)
                                        </td>
                                        <td>
                                            Notes
                                        </td>
                                        <td>
                                            @Html.TextBoxFor(m => m.Notes)
                                        </td>
                                    </tr>
                                    <tr id="loc">
                                        <td>
                                            Location
                                        </td>
                                        <td>
                                            @Html.TextBoxFor(m => m.Coordinates, new { id = "locations" })
                                        </td>
                                        <td>
                                            Image
                                        </td>
                                        <td>
                                            <input type="file" name="file" id="file" accept="image/*" />
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div class="row margin">
                                                <div class="input-field col s12">
                                                    <img src="~/Uploads/MyCallTree/@Model.Images" alt="" height="120px" width="120px" />
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                </table>
                                <div class="section" id="modals-demo">
                                    <div class="row">
                                        <div class="col s12 m8 l9">
                                            <p>
                                                <a href="#modal1" id="setloc" style="display:none" class="waves-effect waves-light btn modal-trigger  light-blue" onclick=' return initialize();'>Location</a>
                                            </p>

                                        </div>
                                    </div>
                                </div>

                                <div class="row">

                                    <div class="input-field col s12">
                                        <div class=" col s6 ">
                                           
                                            <a href="@Url.Action("Index")" class="btn cyan waves-effect waves-light left">
                                                Go Back<i class="mdi-content-send right"></i>
                                            </a>
                                        </div>
                                        <div class=" col s6">
                                            <button name="action" type="submit" class="btn cyan waves-effect waves-light right">Save <i class="mdi-content-send right"></i></button>
                                        </div>
                                    </div>
                                </div>

                                        }
                        </div>
                    </div>
                    <div class="card-content">
                        <a class="btn-floating btn-move-up waves-effect waves-light darken-2 right"><i class="mdi-content-add activator add-row-btn"></i></a>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
<div class="modalTest" id="modal1" style="width:700px;height:600px">
    <div id="maps">
    </div>
</div>
<script type="text/javascript">
    var map;
    function initialize() {
        navigator.geolocation.getCurrentPosition(success);
        function success(position) {
            latlngs = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
            var mapProp = {
                center: latlngs, //Pick up user current Location
                zoom: 5,
                mapTypeId: google.maps.MapTypeId.G_NORMAL_MAP
            };
            map = new google.maps.Map(document.getElementById("maps"), mapProp);
            google.maps.event.addListener(map, 'click', function (e) {
                var latLng = e.latLng;
                $('#locations').val(latLng);
                $('#loc').css('display', 'table-row');
                $('#modal1').hide();
                $('#lean-overlay').hide();
            });
        }
    }
    // google.maps.event.addDomListener(window, "load", initialize);
    google.maps.event.trigger(map, 'resize');
</script>
<script>
    $(document).ready(function () {
        $("#locations").on('click', function () {
            $('#setloc').click();
        });
        $("#HelperID").change(function () {
            $("#MyForm").submit();
        });
    });
</script>