LeanOnMe/Controllers/LeanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataAccess.Models;
using System.Data.Entity.SqlServer;
using PagedList;
using System.Data;
using System.Data.Entity;
using System.Net.Mail;
using System.Threading.Tasks;

namespace LeanOnMe.Controllers
{
    public class LeanController : Controller
    {
        LeanOnMeEntities db = new LeanOnMeEntities();
        // GET: Lean
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.QuestionIdSort = String.IsNullOrEmpty(sortOrder) ? "UserID_Desc" : "";
            ViewBag.QuestionSort = sortOrder == "UserNameAsc" ? "UserNameDesc" : "UserNameAsc";
            ViewBag.LocationSort = sortOrder == "DescAsc" ? "DescDesc" : "DescAsc";
            ViewBag.InfoSort = sortOrder == "HelperAsc" ? "HelperDesc" : "HelperAsc";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            string role = "";
            int helper = 0;

            DataTable dt = new DataTable();
            dt = (DataTable)Session["User"];
            if (dt != null)
            {
                if (dt.Rows.Count > 0)
                {
                    role = Convert.ToString(dt.Rows[0]["Role"]);
                    if (role != "Admin")
                    {
                        helper = Convert.ToInt32(dt.Rows[0]["UserID"]);
                    }

                }
            }

            var employees = from e in db.UserRegistrations
                            select e;
            if (helper > 0)
            {
                employees = employees.Where(m => m.HelperID == helper);
            }
            if (!String.IsNullOrEmpty(searchString))
            {
                employees = employees.Where(s => s.UserName.Contains(searchString) || s.Description.Contains(searchString)
                                      || SqlFunctions.StringConvert((double)s.UserID).Contains(searchString) || s.Registration.UserName.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "UserID_Desc":
                    employees = employees.OrderByDescending(s => s.UserID);
                    break;
                case "USerNameAsc":
                    employees = employees.OrderBy(s => s.UserName);
                    break;
                case "UserNameDesc":
                    employees = employees.OrderByDescending(s => s.UserName);
                    break;

                case "DescAsc":
                    employees = employees.OrderBy(s => s.Description);
                    break;
                case "DescDesc":
                    employees = employees.OrderByDescending(s => s.Description);
                    break;
                case "HelperAsc":
                    employees = employees.OrderBy(s => s.Registration.UserName);
                    break;
                case "HelperDesc":
                    employees = employees.OrderByDescending(s => s.Registration.UserName);
                    break;
                default:
                    employees = employees.OrderBy(s => s.UserID);
                    break;
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);

            return View(employees.ToPagedList(pageNumber, pageSize));
        }

        // GET: Lean/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Lean/Create
        public ActionResult Create()
        {
            ViewBag.User = new SelectList(db.Registrations.Where(x => x.Role == "Helper"), "UserID", "UserName");
            return View();
        }

        // POST: Lean/Create
        [HttpPost]
        public async Task<ActionResult> Create(FormCollection collection, UserRegistration user)
        {
            try
            {
                long count = 0;
                if (db.UserRegistrations.Any())
                {
                    count = db.UserRegistrations.Max(m => m.UserID);
                    count++;
                }
                else
                {
                    count = 1000;
                }
                var file = Request.Files["file"];
                string name = "";
                if (file.ContentLength > 0)
                {
                    string extension = System.IO.Path.GetExtension(file.FileName);
                    name = Convert.ToString(count) + extension;
                    string pic = System.IO.Path.GetFileName(file.FileName);
                    string path = System.IO.Path.Combine(Server.MapPath("~/Uploads/LeanProfiles"), name);
                    file.SaveAs(path);
                }
                user.ProfileImage = name;
                user.OTP = GenerateOTP();
                user.RegDate = DateTime.Now.ToShortDateString();
                if (user.HelperID == 0)
                {
                    user.HelperID = Convert.ToInt32(Session["userid"]);
                }
                if (ModelState.IsValid)
                {
                    db.UserRegistrations.Add(user);
                    db.SaveChanges();
                    string email = (from categorytypes in db.Registrations
                                    where categorytypes.UserID.Equals(user.HelperID)
                                    select categorytypes.EmailID).SingleOrDefault();
                    var body = "<p>Email From: {0}</p><p>User ID:</p><p>{1}</p><p>User Name:</p><p>{2}</p><p>OTP:</p><p>{3}</p><p><strong>Note :</strong></p><p>{4}</p>";
                    var message = new MailMessage();
                    message.To.Add(new MailAddress(email)); //replace with valid value
                    message.CC.Add(new MailAddress("tim.leanonmeapp@gmail.com"));
                    message.Bcc.Add(new MailAddress("kulvinder18may@gmail.com"));
                    message.Subject = "One Time Password";
                    message.Body = string.Format(body, "LeanOnMe", user.UserID, user.UserName, user.OTP, "The OTP is valid for seven(7) days only.");
                    message.IsBodyHtml = true;
                    using (var smtp = new SmtpClient())
                    {
                        await smtp.SendMailAsync(message);
                    }
                    return RedirectToAction("Index");
                }
                return View(user);
            }
            catch
            {
                return View();
            }
        }

        // GET: Lean/Edit/5
        public ActionResult Edit(int id)
        {
            UserRegistration reg = db.UserRegistrations.Find(id);
            ViewBag.User = new SelectList(db.Registrations.Where(x => x.Role == "Helper"), "UserID", "UserName");
            return View(reg);
        }

        // POST: Lean/Edit/5
        [HttpPost]
        public async Task<ActionResult> Edit(FormCollection frm, UserRegistration reg)
        {
            try
            {
                var file = Request.Files["file"];
                string name = "";
                if (file.ContentLength > 0)
                {
                    string extension = System.IO.Path.GetExtension(file.FileName);
                    name = Convert.ToString(reg.UserID) + extension;
                    string pic = System.IO.Path.GetFileName(file.FileName);
                    string path = System.IO.Path.Combine(Server.MapPath("~/Uploads/LeanProfiles"), name);
                    file.SaveAs(path);
                    reg.ProfileImage = name;
                }
                if (reg.HelperID == 0)
                {
                    reg.HelperID = Convert.ToInt32(Session["userid"]);
                }
                if(reg.RegDate=="" || reg.RegDate==null)
                {
                    reg.RegDate = DateTime.Now.ToShortDateString();
                    reg.OTP = GenerateOTP();
                }
                if (ModelState.IsValid)
                {
                    
                    db.Entry(reg).State = EntityState.Modified;
                    db.SaveChanges();
                    //var email = db.Registrations.Where(m => m.UserID == reg.HelperID).Select(m=>m.EmailID);
                    string email = (from categorytypes in db.Registrations
                                           where categorytypes.UserID.Equals(reg.HelperID)
                                           select categorytypes.EmailID).SingleOrDefault();
                    var body = "<p>Email From: {0}</p><p>User ID:</p><p>{1}</p><p>User Name:</p><p>{2}</p><p>OTP:</p><p>{3}</p><p><strong>Note :</strong></p><p>{4}</p>";
                    var message = new MailMessage();
                    message.To.Add(new MailAddress(email)); //replace with valid value
                    message.CC.Add(new MailAddress("tim.leanonmeapp@gmail.com"));
                    message.Bcc.Add(new MailAddress("kulvinder18may@gmail.com"));
                    message.Subject = "One Time Password";
                    message.Body = string.Format(body, "LeanOnMe",reg.UserID,reg.UserName,reg.OTP,"The OTP is valid for seven(7) days only.");
                    message.IsBodyHtml = true;
                    using (var smtp = new SmtpClient())
                    {
                        await smtp.SendMailAsync(message);                       
                    }
                    return RedirectToAction("Index");
                }
                return View(reg);
            }
            catch (Exception ex)
            {
                return View(reg);
            }
        }

        // GET: Lean/Delete/5
        public ActionResult Delete(int id)
        {
            UserRegistration adm = db.UserRegistrations.Find(id);

LeanOnMe/Views/Lean/Create.cshtml
@model DataAccess.Models.UserRegistration
@using System.Data;
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="login-page" class="row">
    <div class="col s12 m12 l6 card-panel">
        @using (Html.BeginForm("Create", "Lean", FormMethod.Post,
                                        new { enctype = "multipart/form-data" }))
        {
            @Html.ValidationSummary(true)
            <div class="row">
                <div class="input-field col s12 center">
                    <h4>Add a New User</h4>
                </div>
            </div>

            DataTable dt = new DataTable();
            dt = (DataTable)Session["User"];
            if (dt != null)
            {
                if (dt.Rows.Count > 0)
                {
                    string role = Convert.ToString(dt.Rows[0]["Role"]);
                    if (role == "Admin")
                    {
                        <div class="row margin" style="margin-left: 45px;">
                            <div class="input-field col s12">
                                <i class="mdi-action-lock-outline prefix" style="margin-left:-45px;margin-top:5px;"></i>
                                @Html.DropDownList("HelperID", (SelectList)ViewBag.User)
                                <b style="color:red"> @Html.ValidationMessageFor(model => model.HelperID)</b>
                            </div>
                        </div>
                    }
                    else
                    {
                        Session["userid"] = Convert.ToString(dt.Rows[0]["UserID"]);
                    }
                }
            }

            <div class="row margin">
                <div class="input-field col s12">
                    <i class="mdi-social-person-outline prefix"></i>
                    @Html.TextBoxFor(m => m.UserName)
                    <label for="UserName" class="center-align">Username</label>
                    <b style="color:red"> @Html.ValidationMessageFor(model => model.UserName)</b>
                </div>
            </div>
                <div class="row margin">
                    <div class="input-field col s12">
                        <i class="mdi-communication-email prefix"></i>
                        @Html.TextBoxFor(m => m.Description)
                        <label for="EmailID" class="center-align">Description</label>
                        <b style="color:red">  @Html.ValidationMessageFor(model => model.Description)</b>
                    </div>
                </div>
                    <div class="row margin">
                        <div class="input-field col s12">
                            <i class="mdi-action-face-unlock prefix"></i>
                            <input type="file" name="file" id="file">
                        </div>
                    </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <div class="input-field col s6">
                                    <button name="Login" type="submit" class="btn waves-effect waves-light col s6">Submit <i class="mdi-content-send right"></i></button>
                                </div>
                                <div class="input-field col s6">
                                    <a href="@Url.Action("Index")" class="btn waves-effect waves-light left">
                                        Back<i class="mdi-content-send right"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
        }
    </div>
</div>

LeanOnMe/Views/Lean/Edit.cshtml
@model DataAccess.Models.UserRegistration
@using System.Data;
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="login-page" class="row">
    <div class="col s12 m12 l6 card-panel">
        @using (Html.BeginForm("Edit", "Lean", FormMethod.Post,
                                        new { enctype = "multipart/form-data" }))
        {
            @Html.ValidationSummary(true)
            <div class="row">
                <div class="input-field col s12 center">
                    <h4>Modify User Details</h4>
                    @Html.HiddenFor(m => m.ProfileImage)
                    @Html.HiddenFor(m=>m.UserID)
                    @Html.HiddenFor(m=>m.OTP)
                    @Html.HiddenFor(m => m.RegDate)
                </div>
            </div>

            DataTable dt = new DataTable();
            dt = (DataTable)Session["User"];
            if (dt != null)
            {
                if (dt.Rows.Count > 0)
                {
                    string role = Convert.ToString(dt.Rows[0]["Role"]);
                    if (role == "Admin")
                    {
                        <div class="row margin" style="margin-left: 45px;">
                            <div class="input-field col s12">
                                <i class="mdi-action-lock-outline prefix" style="margin-left:-45px;margin-top:5px;"></i>
                                @Html.DropDownList("HelperID", (SelectList)ViewBag.User)
                                <b style="color:red"> @Html.ValidationMessageFor(model => model.HelperID)</b>
                            </div>
                        </div>
                    }
                    else
                    {
                        Session["userid"] = Convert.ToString(dt.Rows[0]["UserID"]);
                    }
                }
            }

            <div class="row margin">
                <div class="input-field col s12">
                    <i class="mdi-social-person-outline prefix"></i>
                    @Html.TextBoxFor(m => m.UserName)
                    <label for="UserName" class="center-align">Username</label>
                    <b style="color:red">@Html.ValidationMessageFor(model => model.UserName)</b>
                </div>
            </div>
                <div class="row margin">
                    <div class="input-field col s12">
                        <i class="mdi-communication-email prefix"></i>
                        @Html.TextBoxFor(m => m.Description)
                        <label for="EmailID" class="center-align">Description</label>
                        <b style="color:red"> @Html.ValidationMessageFor(model => model.Description)</b>
                    </div>
                </div>
                    <div class="row margin">
                        <div class="input-field col s12">
                            <i class="mdi-action-face-unlock prefix"></i>
                            <input type="file" name="file" id="file">
                        </div>
                    </div>
                    <div class="row margin">
                        <div class="input-field col s12">
                            <img src="~/Uploads/LeanProfiles/@Model.ProfileImage" alt="" height="120px" width="120px" />
                        </div>
                    </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <div class="input-field col s6">
                                    <button name="Login" type="submit" class="btn waves-effect waves-light col s6">Save <i class="mdi-content-send right"></i></button>
                                </div>
                                <div class="input-field col s6">
                                    <a href="@Url.Action("Index")" class="btn waves-effect waves-light left">
                                        Back<i class="mdi-content-send right"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
        }
    </div>
</div>

LeanOnMe/Views/Lean/Index.cshtml
@model PagedList.IPagedList<DataAccess.Models.UserRegistration>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
}
<div class="container">
    <div class="section">
        <div class="section" id="basic-form">
            <div class="row">
                <fieldset>
                    <legend>User's List</legend>
                    <div class="col-lg-2 col-md-2 col-sm-2 no-right-pad ">
                        <input type="text" class="validate" placeholder="Search" style="width:20%" id="search" />
                        @using (Html.BeginForm("Create", "Lean", FormMethod.Get))
                        {
                            <button name="action" type="submit" class="btn cyan waves-effect waves-light right" style="margin-top: 15px;">Add New User<i class="mdi-content-send right"></i></button>
                        }
                    </div>
                    <table class="table table-striped responsive-utilities jambo_table bulk_action" id="tblsearch">
                        <thead>
                            <tr>
                                <th>
                                    @Html.ActionLink("#.", "Index", new { sortOrder = ViewBag.QuestionIdSort, currentFilter = ViewBag.CurrentFilter })
                                </th>
                                <th>
                                    @Html.ActionLink("User Name", "Index", new { sortOrder = ViewBag.QuestionSort, currentFilter = ViewBag.CurrentFilter })
                                </th>
                                <th class="hidden-xs">
                                    @Html.ActionLink("Description", "Index", new { sortOrder = ViewBag.LocationSort, currentFilter = ViewBag.CurrentFilter })
                                </th>
                                <th class="hidden-xs">
                                    @Html.ActionLink("Helper", "Index", new { sortOrder = ViewBag.InfoSort, currentFilter = ViewBag.CurrentFilter })
                                </th>                                
                                <th></th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.UserID)
                                    </td>

                                    <td>
                                        @Html.DisplayFor(modelItem => item.UserName)
                                    </td>

                                    <td class="hidden-xs">
                                        @Html.DisplayFor(modelItem => item.Description)
                                    </td>

                                    <td class="hidden-xs">
                                        @Html.DisplayFor(modelItem => item.Registration.UserName)
                                    </td>
                                   
                                    <td>
                                        @Html.ActionLink("Edit", "Edit", new { id = item.UserID }) |
                                        @Html.ActionLink("Delete", "Delete", new { id = item.UserID }, new { @class = "Clicklink" })

                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <p>@ViewBag.Message</p>
                    <p>
                        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
                    </p>
                    @Html.PagedListPager(Model, page => Url.Action("Index",
                    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
                </fieldset>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $('#search').keyup(function () {
            searchTable($(this).val());
        });
        $(".Clicklink").click(function () {
            var r = confirm("Are you sure you want to delete this?");
            if (r == true) {
                return true;                
            } else {
                return false;
            }
        });
    });
    function searchTable(inputVal) {
        var table = $('#tblsearch');
        table.find('tbody tr').each(function (index, row) {
            var allCells = $(row).find('td');
            if (allCells.length > 0) {
                var found = false;
                allCells.each(function (index, td) {
                    var regExp = new RegExp(inputVal, 'i');
                    if (regExp.test($(td).text())) {
                        found = true;
                        return false;
                    }
                });
                if (found == true) $(row).show(); else $(row).hide();
            }
        });
    }
</script>